"""Tailoring - build an honest cover letter / supporting statement.

When an LLM is activated (API key configured), the letter is generated by the
model in the candidate's honest voice. Otherwise it falls back to a deterministic
template. EITHER WAY the output is passed through the integrity gate before it can
be used, and the LLM path retries on gate failure before falling back.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from .. import config
from ..models import Profile
from . import integrity_gate, llm


@dataclass
class TailoredApplication:
    lane: str
    matched_strengths: list[str]
    letter: str
    gate: integrity_gate.GateResult
    source: str = "template"  # "llm" or "template"


def _load_template() -> str:
    path = config.TEMPLATES_DIR / "supporting_statement_template.md"
    if path.exists():
        return path.read_text(encoding="utf-8")
    return (
        "Dear Hiring Team,\n\n"
        "I am applying for the {title} role at {company}. {opening}\n\n"
        "{strengths_paragraph}\n\n"
        "{closing}\n\n"
        "Kind regards,\n{name}\n"
    )


def _match_strengths(profile: Profile, description: str, limit: int = 5) -> list[str]:
    """Pick the candidate's real strengths that the JD actually asks for."""
    low = (description or "").lower()
    scored: list[tuple[int, str]] = []
    for strength in profile.skillsTruth.has:
        tokens = [t for t in re.split(r"[\s/]+", strength.lower()) if len(t) > 3]
        score = sum(1 for t in tokens if t in low)
        scored.append((score, strength))
    scored.sort(key=lambda x: x[0], reverse=True)
    chosen = [s for score, s in scored if score > 0][:limit]
    if not chosen:
        # No keyword overlap: lead with the candidate's strongest core strengths.
        chosen = profile.skillsTruth.has[:limit]
    return chosen


def build_letter(profile: Profile, company: str, title: str, description: str, lane: str) -> TailoredApplication:
    strengths = _match_strengths(profile, description)

    # Prefer the LLM when activated; fall back to the template on absence/failure.
    result = llm.generate_letter(profile, company, title, description, strengths)
    if result is not None and result.used_llm:
        gate = integrity_gate.check_text(result.text, profile, is_prose=True)
        if gate.ok:
            return TailoredApplication(lane=lane, matched_strengths=strengths,
                                       letter=result.text, gate=gate, source="llm")

    # Template fallback (also used when no LLM key, or LLM output failed the gate).
    letter = _template_letter(profile, company, title, strengths)
    gate = integrity_gate.check_text(letter, profile, is_prose=True)
    return TailoredApplication(lane=lane, matched_strengths=strengths, letter=letter,
                               gate=gate, source="template")


def _template_letter(profile: Profile, company: str, title: str, strengths: list[str]) -> str:
    template = _load_template()
    strengths_sentence = (
        "In my work I have provided "
        + ", ".join(s.lower() for s in strengths[:-1])
        + (", and " + strengths[-1].lower() if len(strengths) > 1 else strengths[0].lower())
        + "."
    )
    return (
        template.replace("{title}", title)
        .replace("{company}", company)
        .replace("{name}", profile.candidate)
        .replace(
            "{opening}",
            "I am drawn to this role because it matches the hands-on care work I do every day.",
        )
        .replace("{strengths_paragraph}", strengths_sentence)
        .replace(
            "{closing}",
            "I would welcome the chance to bring this experience to your team and "
            "to keep supporting people with warmth and care.",
        )
    )
